[package]
name = "kvs"
version = "0.1.0"
authors = ["Sean Wilkins <sean@swilkins.io>"]
description = "A key-value store"
edition = "2018"

[dependencies]
clap = "2.26.0"
diesel = { version = "*", features = ["sqlite"] }
dotenv = "*"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"